apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ci-cd
  labels:
    app: flask-ci-cd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-ci-cd
  template:
    metadata:
      labels:
        app: flask-ci-cd
    spec:
      containers:
      - name: flask-ci-cd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-ci-cd
spec:
  selector:
    app: flask-ci-cd
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
    nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}

